spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/redis?serverTimezone=UTC&characterEncoding=UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: geniusadmin!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cache:
    type: redis